### ISSUE TITLE
When compiling hackney with erlang.mk, idna keeps being recompiled

### ISSUE THREAD

**Issue by rlipscombe** [benoitc/erlang-idna#10]
It looks like erlang.mk uses the Makefile over any other mechanism (rebar.config, Emakefile), and https://github.com/benoitc/erlang-idna/blob/master/Makefile#L1 causes idna to be cleaned and rebuilt every time. Is this intentional?

**Comment by rlipscombe** [comment]
See https://github.com/ninenines/erlang.mk/issues/471

**Comment by benoitc** [comment]
fixed in 1be96dd84788aacd9339fe9556463f470b950a55 will make a release of hackney with it asap.

**Comment by benoitc** [comment]
@rlipscombe hackney 1.4.8 has been released with this fix
