### ISSUE TITLE
stringprep as dependency

### ISSUE THREAD

**Issue by brigadier** [benoitc/erlang-idna#14]
Is it really that necessary to have nif-based stringprep as a dep of idna and indirectly of hackney? It is used once for unicode normalization, maybe it would be better to leave the normalization for the caller?

**Comment by benoitc** [comment]
no i will revert the change. I had an idea to make the build faster and
using less ram :)

**Comment by benoitc** [comment]
@brigadier b219f73b5fc4e8ec65cf669c9ace217766e03136 reverted it. I will publish a new version later tonight. Sorry for the inconvenience.
