### ISSUE TITLE
can not compile because of misssing dependency unicode_util_compat-0.2.0

### ISSUE THREAD

**Issue by mbike2000ru** [benoitc/erlang-idna#17]
Hello

I came across an error while compiling:
==> idna (compile)
Dependency not available: unicode_util_compat-0.2.0 (undefined)
ERROR: compile failed while processing /var/lib/jenkins/jobs/TEST_acceptor/workspace/acceptor/deps/idna: rebar_abort

**Comment by benoitc** [comment]
i've no error with the latest version right now. how can i reproduce it?

**Comment by mbike2000ru** [comment]
in my rebar.config I have:
 {hackney, ".*", {git, "https://github.com/benoitc/hackney.git", "HEAD"}}
and it automatically pulls idna

**Comment by benoitc** [comment]
hrm ci of hackney is working with latest idna, so is local code. Are you on
windows or maybe a rebar.lock fetching an old version?

-- 
Benoit Chesneau

**Comment by mbike2000ru** [comment]
I am on Ubuntu Linux

**Comment by benoitc** [comment]
I'm not reproducing it. Did you tried from a fresh build ? Also don't use head but the tagged version to make things simpler.

**Comment by mbike2000ru** [comment]
I made
 {hackney, ".*", {git, "https://github.com/benoitc/hackney.git", {tag,"1.8.5"}}}

but it still gives a dependency error during compilation

**Comment by benoitc** [comment]
i still not reproducing the error, even on barrel. Are you sure you actually upgraded idna, sometimes the rebar.lock is using an old version. Also make sure to clean the `_build` folder.
