### ISSUE TITLE
unicode_util_compat requires up to 100 MB in dependencies

### ISSUE THREAD

**Issue by AndrewDryga** [benoitc/erlang-idna#18]
Hi,

We are releasing docker container and trying to keep them small, however, latest changes (adding a `unicode_util_compat` to the deps) to required us to install g++, which increased container size by 100 Mb.

Is there any way to drop it?

**Comment by benoitc** [comment]
you don't need to have g++ installed only Make or Gnu Make. Depending on your system it should be possible. 

Otherwise can't you could build your erlang release in one docker and just copy it to the docker image you deploy? This is what I generally do.

**Comment by benoitc** [comment]
no answer since. closing the issue then.
