### ISSUE TITLE
Probably OTP20-related warnings. Lots of them!

### ISSUE THREAD

**Issue by deadtrickster** [benoitc/erlang-idna#20]
```
_build/default/lib/idna/src/idna_unicode_data.erl:13: Warning: key "<font> 0068" will be overridden in expression
_build/default/lib/idna/src/idna_unicode_data.erl:13: Warning: key "<font> 0068" will be overridden in expression
```

**Comment by deadtrickster** [comment]
Ok, now I'm confused. Can't find idna_unicode_data in this repo. Which version/fork hackney uses?

**Comment by benoitc** [comment]
@deadtrickster hackney is using the latest release.  How can I reproduce your issue? Is this in Erlang?

**Comment by deadtrickster** [comment]
All our erlang projects at the company that use barrel_httpc throw this at compilation.

**Comment by benoitc** [comment]
i didn't reproduce it with barrel but anyway latest stable version should improve the situation. even in elixir.

let me know.

**Comment by benoitc** [comment]
fixed in latest version of idna
