### ISSUE TITLE
Do not require unicode_util_compat when using erlang / otp >= 20?

### ISSUE THREAD

**Issue by exterm** [benoitc/erlang-idna#21]
Hi there, I ran into a problem when upgrading my application to erlang 20. I could not build a release anymore because
```
==> Release failed, during .boot generation:
        Duplicated modules: 
    	unicode_util specified in stdlib and unicode_util_compat
```
I guess `unicode_util_compat` should not be used at all with erlang 20?

I should mention that my application is not using `idna` directly but through `hackney`.

My solution for now has been to stay on erlang 19.

**Comment by benoitc** [comment]
which version are you using? this should be fixed in latest and latest hackney master.

**Comment by benoitc** [comment]
fixed in latest version of idna.
