### ISSUE TITLE
Changelog or upgrade guide

### ISSUE THREAD

**Issue by axelson** [benoitc/erlang-idna#23]
Is it possible to provide a changelog or an upgrade guide? Trying to determine compatibility between version 1.x and 5.x. Is there an overview of what has changed? Are there any breaking changes?

**Comment by benoitc** [comment]
So far the main changes are internals (using the new unicode module). Integrating latest version should be transparent, but I will double check. I will also add a changelog for next +1 version., good idea :)

**Comment by axelson** [comment]
Great thanks! Yes I haven't encountered any breaking changes but since the major version has changed multiple times I wasn't sure if I should expect any.

**Comment by benoitc** [comment]
closing issue, there is now an changelog and some doc showing the compatibility api. Thanks for the feedback!
