### ISSUE TITLE
Project license unclear

### ISSUE THREAD

**Issue by dideler** [benoitc/erlang-idna#27]
[The `app.src` file says BSD](https://github.com/benoitc/erlang-idna/blob/master/src/idna.app.src).

[The `LICENSE` file says MIT](https://github.com/benoitc/erlang-idna/blob/master/LICENSE).

Is the project meant to be dual-licensed or is this a discrepancy?

**Comment by benoitc** [comment]
it should have been MIT. fixed in the current master. Thanks!
