### ISSUE TITLE
License mix-up

### ISSUE THREAD

**Issue by debalance** [benoitc/erlang-idna#33]
Hi,
the text in the LICENSE file is the MIT license, yet in ./src/idna_ucs.erl and ./src/idna.app.src it is called BSD license, which is wrong.

Could you please resolve this?

**Comment by hrieke** [comment]
Some clarification would be great since idna_ucs.erl also contains Apache License 2.0 from Ericsson AB.
If it is copied in, that wonderful (Open Source using Open Source), but please give a clean and clear header so we can follow and ensure that we respect the licenses.

Thanks!

**Comment by benoitc** [comment]
fixed in latest master

**Comment by hrieke** [comment]
Thank you.
Have a great weekend, happy holidays, and a *much better* 2021.
