### ISSUE TITLE
Codepoint not allowed: Emoji domains are not working

### ISSUE THREAD

**Issue by ruudk** [benoitc/erlang-idna#35]
I'm not able to convert emoji domains like:
```elixir
:idna.encode("👁👄👁.fm")
** (exit) {:bad_label, {:context, 'Codepoint 128065 not allowed (\'DISALLOWED\') at posion 0 in [128065,128068,\n                                                            128065]'}}

# Expecting 'xn--mp8hai.fm'`
```

While this works:
```elixir
:idna.encode("über.de")
'xn--ber-goa.de'
```

Am I doing something wrong here or is this not supported?

**Comment by benoitc** [comment]
hrm it works there : 

``
3> idna:encode("über.de") 
3> .
"xn--ber-goa.de"
``

is your shell unicode?

**Comment by ruudk** [comment]
Yes, the example with Uber works fine. But the one with Emoji's doesn't.

I'm using iTerm2 on macOS and that has support for unicode.

**Comment by ruudk** [comment]
Try this:
```elixir
:idna.encode("👁👄👁.fm")
```

**Comment by benoitc** [comment]
i'm not sure that code point (128065) is indeed disallowed in table 11. Maybe updating the table would work. I didn't check it yet.

**Comment by ruudk** [comment]
I'm new to Erlang (only using Elixir atm) so I have no idea how to update the table. Are the instructions somewhere in this repository?

**Comment by ruudk** [comment]
@benoitc if you have any tips how to proceed that would be much appreciated. I can submit a PR once I'm able to update the data.

**Comment by ruudk** [comment]
@benoitc Handled in #36 What do you think? :)
